package cn.edu.suda.scholarsense.subjectregistry.domain;

public enum SubjectRegistryErrorCode {
    SUBJECT_REGISTRY_FORBIDDEN,
    SUBJECT_REGISTRY_NOT_FOUND,
    SUBJECT_REGISTRY_AMBIGUOUS,
    SUBJECT_REGISTRY_VERSION_CONFLICT,
    SUBJECT_REGISTRY_IDEMPOTENCY_MISMATCH,
    SUBJECT_REGISTRY_DEPENDENCY_UNAVAILABLE,
    SUBJECT_REGISTRY_TIME_SOURCE_UNAVAILABLE,
    SUBJECT_REGISTRY_MAPPING_OVERLAP,
    SUBJECT_REGISTRY_INVALID_TRANSITION,
    SUBJECT_REGISTRY_PROTECTION_KEY_UNAVAILABLE,
    SUBJECT_REGISTRY_AUDIT_UNAVAILABLE,
    SUBJECT_REGISTRY_STUDENT_REF_REUSE,
    SUBJECT_REGISTRY_STUDENT_REF_INVALID,
    SUBJECT_REGISTRY_AUTHORITY_PROOF_REQUIRED,
    SUBJECT_REGISTRY_IDENTIFIER_INVALID,
    SUBJECT_REGISTRY_LINEAGE_INVALID
}
