package cn.edu.suda.scholarsense.auditoperations.domain;

public enum FindingCode {
    AUDIT_LEDGER_SEQUENCE_GAP,
    AUDIT_LEDGER_PREVIOUS_HASH_MISMATCH,
    AUDIT_LEDGER_ENTRY_HASH_MISMATCH,
    AUDIT_LEDGER_HEAD_MISMATCH,
    AUDIT_INGESTION_DUPLICATE_CONFLICT,
    AUDIT_INGESTION_CONTRACT_REJECTED,
    AUDIT_INGESTION_BACKLOG
}
