schemaVersion=IDENTITY-AUTHORIZATION-POLICY-1.0.0
identitySessionPolicyVersion=ISP-1.0.0
roleFieldPolicyVersion=RFP-1.0.0
roleMappingVersion=IDENTITY-ROLE-MAPPING-1.0.0
roleMappingDigest=sha256:f09768f88cd6a595791ec6591e65758b85fd8402585c8ffaa053446214895e29
roleMappingResource=identity-role-mapping-1-0-0
