package cn.edu.suda.scholarsense.ingestionquality.domain;

public enum IngestionQualityErrorCode {
    INGESTION_QUALITY_FORBIDDEN,
    INGESTION_QUALITY_INVALID_STATE,
    INGESTION_QUALITY_VERSION_CONFLICT,
    INGESTION_QUALITY_IDEMPOTENCY_MISMATCH,
    INGESTION_QUALITY_DEPENDENCY_UNAVAILABLE,
    INGESTION_QUALITY_CONTRACT_INVALID,
    INGESTION_QUALITY_EVIDENCE_INVALID,
    INGESTION_QUALITY_WINDOW_OVERLAP,
    INGESTION_QUALITY_STALE_FENCING_TOKEN,
    INGESTION_QUALITY_LEASE_EXPIRED
}
