package cn.edu.suda.scholarsense.ingestionquality.domain;

public enum IngestionQualityErrorCode {
    INGESTION_QUALITY_FORBIDDEN,
    INGESTION_QUALITY_INVALID_STATE,
    INGESTION_QUALITY_VERSION_CONFLICT,
    INGESTION_QUALITY_IDEMPOTENCY_MISMATCH,
    INGESTION_QUALITY_DEPENDENCY_UNAVAILABLE,
    INGESTION_QUALITY_CONTRACT_INVALID,
    INGESTION_QUALITY_EVIDENCE_INVALID,
    INGESTION_QUALITY_WINDOW_OVERLAP,
    INGESTION_QUALITY_STALE_FENCING_TOKEN,
    INGESTION_QUALITY_LEASE_EXPIRED,
    INGESTION_QUALITY_BATCH_IDENTITY_CONFLICT,
    INGESTION_QUALITY_BATCH_NOT_FOUND,
    INGESTION_QUALITY_SOURCE_VERSION_REGRESSION,
    INGESTION_QUALITY_BATCH_IMMUTABLE,
    INGESTION_QUALITY_CORRECTION_INVALID,
    INGESTION_QUALITY_CORRECTION_FORK,
    INGESTION_QUALITY_NORMALIZED_FACT_BINDING_INVALID,
    INGESTION_QUALITY_NORMALIZED_FACT_CONFLICT,
    QUALITY_POLICY_ZERO_DENOMINATOR
}
