package cn.edu.suda.scholarsense.ingestionquality.domain;

public enum QualityEligibilityReason {
    ALL_REQUIRED_ELIGIBLE,
    REQUIRED_MEMBER_FUSED,
    REQUIRED_MEMBER_RECOVERING,
    REQUIRED_MEMBER_MISSING,
    REQUIRED_MEMBER_VERSION_GAP,
    ANY_OF_UNSATISFIED,
    THRESHOLD_UNSATISFIED,
    BOOTSTRAP_FUSED,
    FUSE_LATCHED,
    RECOVERY_LATCHED,
    RECOVERY_RELAPSED,
    RECOVERY_COMMAND_ACCEPTED,
    RECOVERY_VALIDATION_APPROVED,
    RECOVERY_FINALIZED
}
