package cn.edu.suda.scholarsense.identityaccess.domain;

public enum ResponsibilityRecipientReason {
    VALID("RESPONSIBILITY_VALID"),
    ZERO_RECIPIENT("RESPONSIBILITY_ZERO_RECIPIENT"),
    MULTIPLE_RECIPIENTS("RESPONSIBILITY_MULTIPLE_RECIPIENTS"),
    INACTIVE_RECIPIENT("RESPONSIBILITY_INACTIVE_RECIPIENT"),
    NON_R1_RECIPIENT("RESPONSIBILITY_NON_R1_RECIPIENT"),
    COLLEGE_MISSING("RESPONSIBILITY_COLLEGE_MISSING"),
    COLLEGE_INACTIVE("RESPONSIBILITY_COLLEGE_INACTIVE"),
    COLLEGE_MISMATCH("RESPONSIBILITY_COLLEGE_MISMATCH"),
    EFFECTIVE_END_REACHED("RESPONSIBILITY_EFFECTIVE_END_REACHED"),
    RECONCILIATION_DIFFERENCES(
            "RESPONSIBILITY_RECONCILIATION_DIFFERENCES"),
    DEPENDENCY_WATERMARK_BEHIND(
            "RESPONSIBILITY_DEPENDENCY_WATERMARK_BEHIND"),
    CLOCK_UNAVAILABLE("RESPONSIBILITY_CLOCK_UNAVAILABLE");

    private final String code;

    ResponsibilityRecipientReason(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
